global using Xunit;
global using animationGeneration;
global using animationGeneration.Models;
global using commonDataModels.Models;
global using inputParsing;
global using inputParsing.Models;
global using sql.executor;
global using tableGeneration;
global using tableGeneration.Models;
